import { NextRequest, NextResponse } from "next/server";
import { AIMessage, HumanMessage } from "@langchain/core/messages";
import { getDemoUserId } from "@/lib/demo/session";
import { FinanceRepository } from "@/lib/repository/FinanceRepository";
import { createOrchestrator } from "@/lib/langchain/orchestrator";

/**
 * The conversational "Plan" surface (Layer 2 of the proposal). Every message
 * runs through the LangGraph Orchestrator, which routes the turn to the
 * Goal Planner or Cash-Flow Interpreter specialist — each grounded so every
 * number traces back to RunwayCalculator / PlanService, never generated by
 * the model.
 */
export async function POST(req: NextRequest) {
  const userId = await getDemoUserId();
  if (!userId) return NextResponse.json({ error: "unauthenticated" }, { status: 401 });

  const { message } = (await req.json()) as { message: string };
  const repo = new FinanceRepository();

  await repo.appendChatMessage(userId, "user", message);
  const history = await repo.getChatHistory(userId);

  const messages = history.map((m) =>
    m.role === "user" ? new HumanMessage(m.content) : new AIMessage(m.content)
  );

  const orchestrator = createOrchestrator(userId);
  const result = await orchestrator.invoke({ messages });

  const lastMessage = result.messages[result.messages.length - 1];
  const finalText = lastMessage?.text ?? "";

  await repo.appendChatMessage(userId, "assistant", finalText);
  return NextResponse.json({ reply: finalText });
}
