import { NextRequest, NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import { getDemoUserId } from "@/lib/demo/session";
import { FinanceRepository } from "@/lib/repository/FinanceRepository";
import { PLAN_TOOLS, executePlanTool } from "@/lib/claude/planTools";

const SYSTEM_PROMPT = `You are the Wio Flow Planner — a conversational assistant that helps a UAE expat customer turn a life goal into a concrete, funded plan.

Hard rule: you never invent a number. Every AED figure, date, or percentage you state must come from a tool call you just made (get_runway_snapshot, list_commitments, compute_goal_tradeoff). If you haven't called the relevant tool yet, call it before answering. Your job is phrasing and judgment, not arithmetic.

Be concise and warm, not corporate. Speak in AED. When you state a trade-off, be explicit and honest about the effect on runway — the proposal's whole premise is that trade-offs are shown, not hidden.

Format your replies in markdown: **bold** the key AED figures and dates so they're scannable, and use a short bullet or numbered list whenever you're presenting more than one option, step, or line item. Keep prose plain otherwise — don't bold whole sentences.`;

/**
 * The conversational "Plan" surface (Layer 2 of the proposal). Claude
 * Opus 4.8, tool-use grounded so every number traces back to
 * RunwayCalculator / PlanService — never generated by the model.
 */
export async function POST(req: NextRequest) {
  const userId = await getDemoUserId();
  if (!userId) return NextResponse.json({ error: "unauthenticated" }, { status: 401 });

  const { message } = (await req.json()) as { message: string };
  const repo = new FinanceRepository();

  await repo.appendChatMessage(userId, "user", message);
  const history = await repo.getChatHistory(userId);

  const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  const messages: Anthropic.MessageParam[] = history.map((m) => ({
    role: m.role,
    content: m.content,
  }));

  let finalText = "";
  for (let iteration = 0; iteration < 5; iteration++) {
    const response = await client.messages.create({
      model: "claude-opus-4-8",
      max_tokens: 1024,
      system: SYSTEM_PROMPT,
      tools: PLAN_TOOLS,
      output_config: { effort: "medium" },
      messages,
    });

    const textBlocks = response.content.filter((b) => b.type === "text");
    finalText = textBlocks.map((b) => (b as Anthropic.TextBlock).text).join("\n");

    if (response.stop_reason !== "tool_use") break;

    messages.push({ role: "assistant", content: response.content });

    const toolUseBlocks = response.content.filter(
      (b): b is Anthropic.ToolUseBlock => b.type === "tool_use"
    );
    const toolResults: Anthropic.ToolResultBlockParam[] = [];
    for (const block of toolUseBlocks) {
      try {
        const result = await executePlanTool(
          userId,
          block.name,
          block.input as Record<string, unknown>
        );
        toolResults.push({
          type: "tool_result",
          tool_use_id: block.id,
          content: JSON.stringify(result),
        });
      } catch (err) {
        toolResults.push({
          type: "tool_result",
          tool_use_id: block.id,
          content: (err as Error).message,
          is_error: true,
        });
      }
    }
    messages.push({ role: "user", content: toolResults });
  }

  await repo.appendChatMessage(userId, "assistant", finalText);
  return NextResponse.json({ reply: finalText });
}
