import { NextRequest, NextResponse } from "next/server";
import { AIMessage, HumanMessage } from "@langchain/core/messages";
import { getDemoUserId } from "@/lib/demo/session";
import { FinanceRepository, type UserBundle } from "@/lib/repository/FinanceRepository";
import { createOrchestrator } from "@/lib/langchain/orchestrator";

/**
 * The conversational "Plan" surface (Layer 2 of the proposal). Every message
 * runs through the LangGraph Orchestrator, which routes the turn to the
 * Goal Planner, Cash-Flow Interpreter, or Policy Q&A specialist — each
 * grounded so every number/claim traces back to a tool call (domain
 * calculators or the policy knowledge base), never generated by the model.
 */
export async function POST(req: NextRequest) {
  const userId = await getDemoUserId();
  if (!userId) return NextResponse.json({ error: "unauthenticated" }, { status: 401 });

  const { message } = (await req.json()) as { message: string };
  const repo = new FinanceRepository();

  await repo.appendChatMessage(userId, "user", message);
  const history = await repo.getChatHistory(userId);

  const messages = history.map((m) =>
    m.role === "user" ? new HumanMessage(m.content) : new AIMessage(m.content)
  );

  // Memoized so every tool call within this one request shares a single
  // fetch instead of re-querying Supabase per tool invocation.
  let cachedBundle: Promise<UserBundle> | null = null;
  const getBundle = () => (cachedBundle ??= repo.getUserBundle(userId));

  const orchestrator = createOrchestrator(getBundle);
  const result = await orchestrator.invoke(
    { messages },
    { runName: "plan-chat", tags: ["plan-chat"], metadata: { userId } }
  );

  const lastMessage = result.messages[result.messages.length - 1];
  const finalText = lastMessage?.text ?? "";

  await repo.appendChatMessage(userId, "assistant", finalText);
  return NextResponse.json({ reply: finalText });
}
